### ISSUE TITLE
1.40 can't upload any file

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#166]
Since i update to 1.40 i can't upload any file. Error 403 access denied.
Cache cleaned + logoff and logon. Still not work.

In the same host i have another version running, the 1.37 and is working good.

**Comment by kalcaddle** [comment]
When asking questions, try to provide the operating environment [server: system and version, php version, web server and version; client: operating system and version, browser or App type and version]; for example
```
server: centos 8.1 / php8.1 / nginx 1.2 / mysql 5.6
client: windows 11 / chrome 101
```

We did not find this problem, it may be caused by server compatibility issues.
1.40 In the upload part, in order to optimize the speed, we use binary upload by default. It may be optimized with this one, provide the server operating environment, and we will make it compatible.
It would be better if you can provide an access site and account.email to: warlee#kodcloud.com

**Comment by kalcaddle** [comment]
we still cannot find this problem , &nbsp;please email to me a temp site/admin account , thanks.




------------------ Original ------------------
From: Gianluigi ***@***.***&gt;
Date: Thu,Jun 1,2023 11:39 PM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: warlee ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] 1.40 can't upload any file (Issue #166)





  
When asking questions, try to provide the operating environment [server: system and version, php version, web server and version; client: operating system and version, browser or App type and version]
  
Sorry for that, but i thought was useless considering what i said before: "In the same host i have another version running, the 1.37 and is working good". This means that in the SAME HOST i have TWO KodBox, one 1.40 and one 1.37. The 1.37 works good, the 1.40 no more after the update.
 But for be more detailed as possible, here are all the details:
 
  
We did not find this problem, it may be caused by server compatibility issues. 1.40 In the upload part, in order to optimize the speed, we use binary upload by default. It may be optimized with this one, provide the server operating environment, and we will make it compatible. It would be better if you can provide an access site and account(email: warlee#kodcloud.com)
  
Take a look at the details, if there is all ok and still can't find the problem, i will send the email with a temp account to give you access.

**Comment by RallyTuning** [comment]
1.41 was fixed, but since 1.42 its broken again. I have update to 1.44 just now and still can't upload (error 403, access denied. Same problem as the original post)

**Comment by RallyTuning** [comment]
@kalcaddle Another info, as the first post say, i still have another host with the old 1.37 version and there is still working 100%. I'm thinking to copy-paste this version to my main host and stay with this forever :D

**Comment by kalcaddle** [comment]
we did not find the problem, it may be caused by server compatibility. &nbsp;Provide a site address if convenient. As well as a temporary administrator account, let's test it out.


email &nbsp;to: &nbsp;warlee#kodcloud.com

杭州可道云网络有限公司


------------------ Original ------------------
From: Gianluigi ***@***.***&gt;
Date: Sat,Sep 30,2023 6:20 AM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: warlee ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] 1.40 can't upload any file (Issue #166)





 
@kalcaddle Another info, as the first post say, i still have another host with the old 1.37 version and there is still working 100%. I'm thinking to copy-paste this version to my main host and stay with this forever :D

**Comment by kalcaddle** [comment]
This issue has been handled with compatibility and runs well on similar servers.  Through the website you provided earlier, we found that you have not enabled or disabled the "client" plugin.  The relevant functional adaptation is written in this plugin. Please enable or enable the "client" plugin in the plugin center.

If you really want to disable this plugin You can manually configure the upload method.
Add the following content to config/setting_ User.php

```
$config ['settings'] ['upload '] ['sendAsBinary']=0;
```

**Comment by RallyTuning** [comment]
@kalcaddle Thanks for the detailed answer. After enabled the Client plugin, the upload works again. I have disabled it because i don't use the PC app, just the web interface, so i thought would be a performance saver to disable plugin that i don't use. But i will keep it enabled now.
In any case, i will save the `$config` entry, just in case i need it in future. Thanks!
