### ISSUE TITLE
8月7日我更新完之后不能压缩文件?

### ISSUE THREAD

**Issue by liuyike98** [kalcaddle/kodbox#18]
压缩文件就右上角提示 "不存在",是啥原因?更新前还啥事没有

**Comment by kalcaddle** [comment]
没发现该问题，可能是你服务器相关问题，对比在官网demo测试看看。
这个版本也没有修改解压缩部分。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liuyike98 ***@***.***&gt;
发送时间: 2021年8月8日 15:59
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[kalcaddle/kodbox] 8月7日我更新完之后不能压缩文件? (#18)





 
压缩文件就右上角提示 "不存在",是啥原因?更新前还啥事没有
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
