### ISSUE TITLE
code editor themes not working

### ISSUE THREAD

**Issue by xcoders-hub** [kalcaddle/kodbox#4]
I saw that on the new update the code editor themes is not working it shows just back bg and white text. Please fix this issue.

**Comment by kalcaddle** [comment]
We didn't find the problem,
 it could be caused by your network load too slow or missing files

![image](https://user-images.githubusercontent.com/3761968/114980542-32040b00-9ebf-11eb-9291-f3f5f95f2e1f.png)

![image](https://user-images.githubusercontent.com/3761968/114980384-f6694100-9ebe-11eb-9c55-84c3d3d0cf41.png)

**Comment by kalcaddle** [comment]
or it's a file type that not support highlight
you can change at here:
![image](https://user-images.githubusercontent.com/3761968/114980868-b48cca80-9ebf-11eb-932a-bd60e71e4ab3.png)
