### ISSUE TITLE
文件直传对象存储

### ISSUE THREAD

**Issue by cxw620** [kalcaddle/kodbox#47]
设置开启了文件直传不经过服务器，但是上传下载文件还是走服务器流量。这个是设计就是如此还是bug？而且腾讯云的对象存储似乎本来就支持断点续传

**Comment by kalcaddle** [comment]
是否中转还取决于对象存储是否支持，还和文件大小有关。
kodbox确保上传成功会采用最组合佳策略。觉得不好可以自行编写插件实现存储挂载，具体参考onedrive，百度网盘等插件



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: 陈寒彤 ***@***.***&gt;
发送时间: 2021年11月27日 00:52
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 文件直传对象存储 (Issue #47)





 
设置开启了文件直传不经过服务器，但是上传下载文件还是走服务器流量。这个是设计就是如此还是bug？而且腾讯云的对象存储似乎本来就支持断点续传
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
