### ISSUE TITLE
Cookies and embed websites

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#48]
So, i have added some websites in the left menu bar, these websites are opened in embed mode (or in a modal window) but they cant save cookies?
Example: I have added my email host website, after i login, he kept redirect me to the login page, instead of mail list. Same with settings website: i have added another website with color background changed, if i refresh the page, the color is back to default. Another website ask me to accept cookies, i accept and the message go away, but if i refresh the website or change page, the message come again.
This means the modal window or embed EXTERNAL websites, cant save cookies in kodbox?

**Comment by kalcaddle** [comment]
not kodbox
Chrome &nbsp;80,samesite,iframe &nbsp;not support cookie now.



杭州可道云网络有限公司


------------------ Original ------------------
From: Gianluigi ***@***.***&gt;
Date: Sat,Nov 27,2021 1:17 AM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] Cookies and embed websites (Issue #48)





 
So, i have added some websites in the left menu bar, these websites are opened in embed mode (or in a modal window) but they cant save cookies?
 Example: I have added my email host website, after i login, he kept redirect me to the login page, instead of mail list. Same with settings website: i have added another website with color background changed, if i refresh the page, the color is back to default. Another website ask me to accept cookies, i accept and the message go away, but if i refresh the website or change page, the message come again.
 This means the modal window or embed EXTERNAL websites, cant save cookies in kodbox?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RallyTuning** [comment]
Will be supported in the future?

**Comment by kalcaddle** [comment]
all by chrome. website can not do anything.  
https://stackoverflow.com/questions/45094712/iframe-not-reading-cookies-in-chrome
