### ISSUE TITLE
Why are all resource files referenced by static URL??

### ISSUE THREAD

**Issue by lujiaxing** [kalcaddle/kodbox#50]
![image](https://user-images.githubusercontent.com/7188738/145674689-c73b8e0f-17f5-4b07-9e25-df560730dbe4.png)

Generally, resource files can be referenced by relative url like "/static/images/icon/fav.png". But for KodBox, all resource files (image, css, etc...) are hard-coded in every page. That makes it difficult to access with different domain names.

In my case, I deployed one on a server, if i access through the Internet, i should access through HTTPS, but it is not required for intranet access. But i tried to access from internet via HTTPS, i found that all resource files are referenced by http, that causes the page to fail to load at all. Because mixed content are prohibited by modern browser.

Why? Any way to configure it to "load resources by relative url"?

**Comment by kalcaddle** [comment]
config &nbsp;cdn path.
/data/config/setting_user.php
$config['settings']['staticPath'] ="http://cdn.test.com/static/";
https://doc.kodcloud.com/v2/#/help/options

杭州可道云网络有限公司


------------------ Original ------------------
From: 阿星～ ***@***.***&gt;
Date: Sat,Dec 11,2021 7:40 PM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] Why are all resource files referenced by static URL?? (Issue #50)





 

 
Generally, resource files can be referenced by relative url like "/static/images/icon/fav.png". But for KodBox, all resource files (image, css, etc...) are hard-coded in every page. That makes it difficult to access with different domain names.
 
In my case, I deployed one in a server, if i access through the Internet, i should access through HTTPS, but it is not required for intranet access. But i tried to access from internet, i found that all resource files are referenced via http, but it's prohibited by modern browser.
 
Why? And any way to configure it to "load resources by relative url"?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
